FROM golang:1.25.7-alpine

RUN apk update && apk upgrade && \
    apk --update add git make bash build-base postgresql-client

RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

ENV PATH=$PATH:/go/bin

WORKDIR /project

ENTRYPOINT ["/project/init.sh"]
