// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (user_id, amount, currency, status, destination)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, amount, currency, status, destination, created_at
`

type CreatePaymentParams struct {
	UserID      int32
	Amount      pgtype.Numeric
	Currency    string
	Status      string
	Destination string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.Destination,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Destination,
		&i.CreatedAt,
	)
	return i, err
}
