// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	ID          pgtype.UUID
	UserID      int32
	Amount      pgtype.Numeric
	Currency    string
	Status      string
	Destination string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
